CREATE DATABASE IF NOT EXISTS cowlist2;

USE cowlist2;

CREATE TABLE IF NOT EXISTS cows (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  cow_name VARCHAR(50) NOT NULL,
  cow_description VARCHAR(200) NOT NULL
);

